### ISSUE TITLE
Cannot find module 'inflection'

### ISSUE THREAD

**Issue by RELATO** [POJOa/Juicy#4]
Hi,

Could you help?

Macintosh:Juicy home$ npm -v
3.10.3
Macintosh:Juicy home$ node -v
v6.4.0

Macintosh:Juicy home$ node app/app.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'inflection'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/home/IdeaProjects/Juicy/app/lib/express-restify-mongoose.js:5:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by RELATO** [comment]
I just found out. 

Just run:
npm install inflection

and

node app/app

Congrats! Very good job!
